knn:
  use_standard_scaler: true
  grid:
    n_neighbors: [3, 5, 7, 9]
    weights: ["uniform", "distance"]
    p: [1, 2]
    
logistic:
  use_standard_scaler: true
  grid:
    penalty: ["l2"]
    C: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
    solver: ["lbfgs"]
    max_iter: [1000]