models:
  naive_bayes:
    enabled: true
    class_path: "src.models.naive_bayes.NaiveBayesClassifier"
    use_scaler: false
    hyperparameters:
      var_smoothing:
        - 1.0e-9
        - 1.0e-8
        - 1.0e-7
        - 1.0e-6
