knn:
  use_standard_scaler: true
  grid:
    n_neighbors: [3, 5, 7, 9]
    weights: ["uniform", "distance"]
    p: [1, 2]
    
logistic:
  use_standard_scaler: true
  grid:
    penalty: ["l2"]
    C: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
    solver: ["lbfgs"]
    max_iter: [1000]

mlp:
  use_standard_scaler: true
  grid:
    hidden_layer_sizes:
      - [50]
      - [100]
      - [50, 50]
      - [100, 50]
    activation: ["relu", "tanh"]
    alpha: [0.0001, 0.001, 0.01]
    learning_rate_init: [0.001, 0.01]
    solver: ["adam"]
